apiName: "Peters API"

assets:
  mappings:
    /assets: /
  overrides:
    /: ../workshop-client/public_html/

server:
  rootPath: /api/*
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081